# Generated by Django 3.1.1 on 2020-09-10 19:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dzialki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('identyfikator', models.CharField(max_length=100)),
                ('powierzchnia', models.FloatField()),
                ('teryt', models.CharField(max_length=7)),
                ('numer', models.CharField(max_length=50)),
                ('wojewodztwo', models.CharField(max_length=254)),
                ('powiat', models.CharField(max_length=254)),
                ('gmina', models.CharField(max_length=254)),
                ('data_od', models.DateField()),
                ('length', models.FloatField()),
                ('area', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
