# Generated by Django 3.1.1 on 2020-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozwolenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_urzad', models.CharField(max_length=50)),
                ('nazwa_organu', models.CharField(max_length=50)),
                ('adres_organu', models.CharField(max_length=50)),
                ('data_wplywu_wniosku', models.DateField()),
                ('numer_decyzji_urzedu', models.CharField(max_length=50)),
                ('data_wydania_decyzji', models.DateField()),
                ('nazwisko_inwestora', models.CharField(max_length=50)),
                ('imie_inwestora', models.CharField(max_length=50)),
                ('nazwa_inwestor', models.CharField(max_length=50)),
                ('wojewodztwo', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=50)),
                ('terc', models.CharField(max_length=50)),
                ('cecha', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('ulica_dalej', models.CharField(max_length=50)),
                ('nr_domu', models.CharField(max_length=50)),
                ('rodzaj_inwestycji', models.CharField(max_length=50)),
                ('kategoria', models.CharField(max_length=50)),
                ('nazwa_zamierzenia_bud', models.CharField(max_length=50)),
                ('nazwa_zam_budowlanego', models.CharField(max_length=50)),
                ('kubatura', models.FloatField()),
                ('projektant_nazwisko', models.CharField(max_length=50)),
                ('projektant_imie', models.CharField(max_length=50)),
                ('projektant_numer_uprawnien', models.CharField(max_length=50)),
                ('jednostka_numer_ew', models.CharField(max_length=50)),
                ('obreb_numer', models.CharField(max_length=50)),
                ('numer_dzialki', models.CharField(max_length=50)),
                ('kod_dzialki', models.CharField(max_length=50)),
                ('numer_arkusza_dzialki', models.CharField(max_length=50)),
                ('jednostka_stara_numeracja_z_wniosku', models.CharField(max_length=50)),
                ('stara_numeracja_obreb_z_wniosku', models.CharField(max_length=50)),
                ('stara_numeracja_dzialka_z_wniosku', models.CharField(max_length=50)),
            ],
        ),
    ]
