# Generated by Django 3.1.1 on 2020-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0002_pozwolenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='cecha',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='imie_inwestora',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='jednostka_numer_ew',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='kategoria',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='miasto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwa_zam_budowlanego',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwa_zamierzenia_bud',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwisko_inwestora',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nr_domu',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='numer_arkusza_dzialki',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='numer_decyzji_urzedu',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='numer_dzialki',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='obreb_numer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_imie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_nazwisko',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_numer_uprawnien',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='rodzaj_inwestycji',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='terc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='ulica',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='ulica_dalej',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='wojewodztwo',
            field=models.CharField(max_length=20),
        ),
    ]
