# Generated by Django 3.1.1 on 2020-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0004_auto_20200926_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='cecha',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='jednostka_stara_numeracja_z_wniosku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nr_domu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='numer_arkusza_dzialki',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_imie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_nazwisko',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_numer_uprawnien',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='stara_numeracja_dzialka_z_wniosku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='stara_numeracja_obreb_z_wniosku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='ulica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='ulica_dalej',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
