# Generated by Django 3.1.1 on 2020-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0005_auto_20200926_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='kubatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
