# Generated by Django 3.1.1 on 2020-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0006_auto_20200926_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='terc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
