# Generated by Django 3.1.1 on 2020-09-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0008_auto_20200930_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PozwoleniaGeom',
        ),
    ]
