# Generated by Django 3.1.1 on 2020-09-30 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0009_delete_pozwoleniageom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PozwoleniaGeom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_urzad', models.CharField(max_length=50)),
                ('nazwa_organu', models.CharField(max_length=50)),
                ('adres_organu', models.CharField(max_length=50)),
                ('data_wplywu_wniosku', models.DateField()),
                ('numer_decyzji_urzedu', models.CharField(max_length=25)),
                ('data_wydania_decyzji', models.DateField()),
                ('nazwisko_inwestora', models.CharField(blank=True, max_length=20, null=True)),
                ('imie_inwestora', models.CharField(blank=True, max_length=20, null=True)),
                ('nazwa_inwestor', models.CharField(blank=True, max_length=50, null=True)),
                ('wojewodztwo', models.CharField(max_length=20)),
                ('miasto', models.CharField(max_length=20)),
                ('terc', models.CharField(blank=True, max_length=10, null=True)),
                ('cecha', models.CharField(blank=True, max_length=5, null=True)),
                ('ulica', models.CharField(blank=True, max_length=20, null=True)),
                ('ulica_dalej', models.CharField(blank=True, max_length=20, null=True)),
                ('nr_domu', models.CharField(blank=True, max_length=10, null=True)),
                ('rodzaj_inwestycji', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=8)),
                ('nazwa_zamierzenia_bud', models.CharField(max_length=512)),
                ('nazwa_zam_budowlanego', models.CharField(max_length=512)),
                ('kubatura', models.FloatField(blank=True, null=True)),
                ('projektant_nazwisko', models.CharField(blank=True, max_length=20, null=True)),
                ('projektant_imie', models.CharField(blank=True, max_length=20, null=True)),
                ('projektant_numer_uprawnien', models.CharField(blank=True, max_length=25, null=True)),
                ('jednostka_numer_ew', models.CharField(max_length=10)),
                ('obreb_numer', models.CharField(max_length=10)),
                ('numer_dzialki', models.CharField(max_length=10)),
                ('identyfikator', models.CharField(max_length=50)),
                ('numer_arkusza_dzialki', models.CharField(blank=True, max_length=10, null=True)),
                ('jednostka_stara_numeracja_z_wniosku', models.CharField(blank=True, max_length=50, null=True)),
                ('stara_numeracja_obreb_z_wniosku', models.CharField(blank=True, max_length=50, null=True)),
                ('stara_numeracja_dzialka_z_wniosku', models.CharField(blank=True, max_length=50, null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
