# Generated by Django 3.1.1 on 2020-10-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0010_pozwoleniageom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozwoleniageom',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
