# Generated by Django 3.1.1 on 2020-10-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0012_pozwolenia_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwa_inwestor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='nazwa_inwestor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
