# Generated by Django 3.1.1 on 2020-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0013_auto_20201002_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='miasto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='ulica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='wojewodztwo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='miasto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='ulica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='wojewodztwo',
            field=models.CharField(max_length=50),
        ),
    ]
