# Generated by Django 3.1.1 on 2020-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0015_auto_20201002_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='rodzaj_inwestycji',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='rodzaj_inwestycji',
            field=models.CharField(max_length=250),
        ),
    ]
