# Generated by Django 3.1.1 on 2020-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0017_auto_20201002_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='rodzaj_inwestycji',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='rodzaj_inwestycji',
            field=models.CharField(max_length=512),
        ),
    ]
