# Generated by Django 3.1.1 on 2020-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0018_auto_20201002_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwa_inwestor',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='nazwa_inwestor',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
