# Generated by Django 3.1.1 on 2020-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0019_auto_20201002_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='imie_inwestora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwisko_inwestora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_imie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_nazwisko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='ulica_dalej',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='imie_inwestora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='nazwisko_inwestora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='projektant_imie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='projektant_nazwisko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='ulica_dalej',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
