# Generated by Django 3.1.1 on 2020-10-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0022_auto_20201002_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='miasto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='miasto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
