# Generated by Django 3.1.1 on 2020-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0025_auto_20201002_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='kategoria',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='kategoria',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
