# Generated by Django 3.1.1 on 2020-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0027_auto_20201002_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='jednostka_numer_ew',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
