# Generated by Django 3.1.1 on 2020-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0029_auto_20201002_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwa_zam_budowlanego',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pozwolenia',
            name='nazwa_zamierzenia_bud',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='nazwa_zam_budowlanego',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='nazwa_zamierzenia_bud',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
