# Generated by Django 3.1.1 on 2020-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0030_auto_20201002_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='stara_numeracja_dzialka_z_wniosku',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='stara_numeracja_dzialka_z_wniosku',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
