# Generated by Django 3.1.1 on 2020-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0032_auto_20201002_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozwolenia',
            name='projektant_numer_uprawnien',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pozwoleniageom',
            name='projektant_numer_uprawnien',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
