# Generated by Django 3.1.1 on 2020-10-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0033_auto_20201002_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozwoleniageom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pozwoleniageom',
            name='mpoly',
        ),
    ]
