# Generated by Django 3.1.1 on 2020-10-04 08:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0034_auto_20201004_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozwoleniageom',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pozwoleniageom',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
