# Generated by Django 3.1.1 on 2020-10-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0035_auto_20201004_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozwoleniageom',
            name='mpoly',
        ),
    ]
