# Generated by Django 3.1.1 on 2020-10-04 09:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0036_remove_pozwoleniageom_mpoly'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozwoleniageom',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pozwoleniageom',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pozwoleniageom',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
