# Generated by Django 3.1.1 on 2020-10-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0037_auto_20201004_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dzialki',
            name='gid',
        ),
    ]
