# Generated by Django 3.1.1 on 2020-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0038_remove_dzialki_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wnioski',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_ewidencyjny_system', models.CharField(max_length=50)),
                ('numer_ewidencyjny_urzad', models.CharField(max_length=50)),
                ('data_wplywu_wniosku_do_urzedu', models.DateField()),
                ('nazwa_organu', models.CharField(max_length=50)),
                ('wojewodztwo_objekt', models.CharField(max_length=50)),
                ('objekt_kod_pocztowy', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=50, null=True)),
                ('terc', models.CharField(blank=True, max_length=50, null=True)),
                ('cecha', models.CharField(blank=True, max_length=5, null=True)),
                ('ulica', models.CharField(blank=True, max_length=50, null=True)),
                ('ulica_dalej', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_domu', models.CharField(blank=True, max_length=50, null=True)),
                ('kategoria', models.CharField(max_length=10, null=True)),
                ('nazwa_zam_budowlanego', models.CharField(max_length=512, null=True)),
                ('rodzaj_zam_budowlanego', models.CharField(max_length=10000, null=True)),
                ('kubatura', models.FloatField(blank=True, null=True)),
                ('stan', models.CharField(max_length=500)),
                ('jednostki_numer', models.CharField(max_length=50, null=True)),
                ('obreb_numer', models.CharField(max_length=50, null=True)),
                ('numer_dzialki', models.CharField(max_length=50, null=True)),
                ('identyfikator', models.CharField(max_length=50, null=True)),
                ('numer_arkusza_dzialki', models.CharField(blank=True, max_length=50, null=True)),
                ('nazwisko_projektanta', models.CharField(blank=True, max_length=50, null=True)),
                ('imie_projektanta', models.CharField(blank=True, max_length=50, null=True)),
                ('projektant_numer_uprawnien', models.CharField(blank=True, max_length=200, null=True)),
                ('projektant_pozostali', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
    ]
