# Generated by Django 3.1.1 on 2020-10-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0039_wnioski'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wnioski',
            old_name='objekt_kod_pocztowy',
            new_name='obiekt_kod_pocztowy',
        ),
    ]
