# Generated by Django 3.1.1 on 2020-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0040_auto_20201014_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wnioski',
            name='obiekt_kod_pocztowy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
