# Generated by Django 3.1.2 on 2020-11-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0042_wnioskigeom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(null=True)),
                ('total_updated_pozwolenia', models.IntegerField(null=True)),
                ('total_skipped_pozwolenia', models.IntegerField(null=True)),
                ('total_failed_pozwolenia', models.IntegerField(null=True)),
                ('total_updated_wnioski', models.IntegerField(null=True)),
                ('total_skipped_wnioski', models.IntegerField(null=True)),
                ('total_failed_wnioski', models.IntegerField(null=True)),
            ],
        ),
    ]
