# Generated by Django 3.1.2 on 2020-11-09 00:05

from django.db import migrations
import polyserver_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0046_auto_20201107_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='updated_at',
            field=polyserver_api.models.DateTimeWithoutTZField(null=True),
        ),
    ]
