# Generated by Django 3.1.2 on 2020-11-09 21:22

from django.db import migrations, models
import polyserver_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0047_auto_20201109_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', polyserver_api.models.DateTimeWithoutTZField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ipdata',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
