# Generated by Django 3.1.3 on 2020-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0048_auto_20201109_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
