# Generated by Django 3.1.3 on 2020-11-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyserver_api', '0049_auto_20201110_2216'),
        ('polyserver_api', '0049_auto_20201112_1111'),
    ]

    operations = [
    ]
